### ISSUE TITLE
 Failed to minify the code with Create React App

### ISSUE THREAD

**Issue by pepesenaris** [sindresorhus/p-min-delay#4]
Could you publish a pre-compiled version to npm as recommended [here](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify)?

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

I'm sorry that `create-react-app` is lacking in this aspect, but it's up to them to support the community. Each package should not be required to specially support `create-react-app`. Please do open an issue on `create-react-app` about this pain point.
