### ISSUE TITLE
Distributed source should contain an ES5 target

### ISSUE THREAD

**Issue by isaachinman** [sindresorhus/p-min-delay#8]
Hi there - I've just discovered that the distributed source of this package contains keywords like `const`, which are breaking our build in ES5 browsers.

I suppose the assumption was that people using promises would be targeting modern browsers, but there are also valid use cases where promises are polyfilled and the target is ES5.

Would the maintainers of this package be open to adding a build step that also transpiles to an ES5 target? Users could then import from a different path if they desire.

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

If you use Create React App, upgrade to [Create React App v2](https://reactjs.org/blog/2018/10/01/create-react-app-v2.html). It supports automatic transpilation of dependencies, which will make this package *just work*.

**Comment by isaachinman** [comment]
I agree with you wholeheartedly that in the long term, the JavaScript world should shift to distributing "real" source, and leaving transpilation/targets up to the end user.

However, that's simply not the current state of things, and the current status quo is to not transpile dependencies. Restricted keywords (in ES5) caught me out from this module. Would be good to at least put a disclaimer in your README.

Thanks for a quick response.

**Comment by dcollien** [comment]
+1 for the disclaimer. Also caught out by this issue. It's so little code... I ended up copy-pasting it into the codebase.
