### ISSUE TITLE
Spread operator throws script error on Microsoft Edge

### ISSUE THREAD

**Issue by chdwck** [sindresorhus/p-min-delay#9]
### Problem
This line https://github.com/sindresorhus/p-min-delay/blob/0f913d8b3db3b411944d8c9447d56fc1b3dd23c8/index.js#L7 doesn't have a polyfill and breaks on microsoft edge.

### To fix
* Add a polyfill or use `Object.assign()`

### Acceptance Criteria
- [ ] Can use `p-min-delay` package on Microsoft edge

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

If you use Create React App, upgrade to [Create React App v2](https://reactjs.org/blog/2018/10/01/create-react-app-v2.html). It supports automatic transpilation of dependencies, which will make this package *just work*.
